### ISSUE TITLE
improve error message

### ISSUE THREAD

**Issue by javeme** [hugegraph/hugegraph-loader#126]
```
$ bin/hugegraph-loader 
Exception in thread "main" com.beust.jcommander.ParameterException: The following options are required: [-f | --file], [-g | --graph]
	at com.beust.jcommander.JCommander.validateOptions(JCommander.java:388)
	at com.beust.jcommander.JCommander.parse(JCommander.java:357)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at com.baidu.hugegraph.loader.executor.LoadContext.parseCheckOptions(LoadContext.java:136)
	at com.baidu.hugegraph.loader.executor.LoadContext.<init>(LoadContext.java:69)
	at com.baidu.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:70)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:65)
```

```
$ bin/hugegraph-loader -g
Exception in thread "main" com.beust.jcommander.ParameterException: Expected a value after parameter -g
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:925)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:894)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:724)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at com.baidu.hugegraph.loader.executor.LoadContext.parseCheckOptions(LoadContext.java:136)
	at com.baidu.hugegraph.loader.executor.LoadContext.<init>(LoadContext.java:69)
	at com.baidu.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:70)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:65)
```

**Comment by Linary** [comment]
After improve

```
$ bin/hugegraph-loader.sh -g hugegraph

Failed to start loading, cause: The following option is required: [-f | --file]
```
