### ISSUE TITLE
loader  不支持 AUTOMATIC id strategy？ 

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph-loader#127]
在[文档](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html)中没有明确说明hugegraph loader 不支持AUTOMATIC Id 策略，但是当设计schema时，如果不指定顶点Id策略(默认为AUTOMATIC Id 策略）， 会报如下错误：
> vertices has been loaded : 3279
ERROR: Failed to load
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported AUTOMATIC id strategy for hugegraph-loader
	at com.baidu.hugegraph.loader.builder.VertexBuilder.checkIdField(VertexBuilder.java:134)
	at com.baidu.hugegraph.loader.builder.VertexBuilder.<init>(VertexBuilder.java:45)
	at com.baidu.hugegraph.loader.builder.ElementBuilder.of(ElementBuilder.java:78)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:159)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:132)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:89)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66)

**Comment by javeme** [comment]
@chencjiajy 是的，自动生成id目前loader还不支持，自动生成id时建议使用client或api的方式插入数据。
