### ISSUE TITLE
Load Error 

### ISSUE THREAD

**Issue by cyberpsyche** [hugegraph/hugegraph-loader#129]
请问以下的导入数据错误是何原因呢？？ struct.json和schema.groovy 应该没有问题。

Sams-MBP:hugegraph-loader-0.10.0 sam$ ./bin/hugegraph-loader -g hugegraph -f test/struct.json -s test/schema.groovy

ERROR: Failed to load
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: com.baidu.hugegraph.driver.GraphManager.schema() is applicable for argument types: () values: []
Possible solutions: sleep(long), sleep(long, groovy.lang.Closure), every(), grep(), dump()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at Script1.run(Script1.groovy:2)
	at com.baidu.hugegraph.loader.executor.GroovyExecutor.execute(GroovyExecutor.java:58)
	at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:118)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:85)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66)

**Comment by javeme** [comment]
@cyberpsyche 看起来是语法错误，请贴出schema.groovy出错部分看看

**Comment by cyberpsyche** [comment]
schema.groovy如下，但在hugegraph_studio中执行是没有问题的呀，完全是与教程中例子相同的。

// PropertyKey
graph.schema().propertyKey("name").asText().ifNotExist().create()
graph.schema().propertyKey("age").asInt().ifNotExist().create()
graph.schema().propertyKey("addr").asText().ifNotExist().create()
graph.schema().propertyKey("lang").asText().ifNotExist().create()
graph.schema().propertyKey("tag").asText().ifNotExist().create()
graph.schema().propertyKey("weight").asFloat().ifNotExist().create()

// VertexLabel
graph.schema().vertexLabel("person").properties("name", "age", "addr", "weight").useCustomizeStringId().ifNotExist().create()
graph.schema().vertexLabel("software").properties("name", "lang", "tag", "weight").primaryKeys("name").ifNotExist().create()
graph.schema().vertexLabel("language").properties("name", "lang", "weight").primaryKeys("name").ifNotExist().create()

// EdgeLabel
graph.schema().edgeLabel("knows").sourceLabel("person").targetLabel("person").properties("weight").ifNotExist().create()
graph.schema().edgeLabel("created").sourceLabel("person").targetLabel("software").properties("weight").ifNotExist().create()
graph.schema().edgeLabel("contains").sourceLabel("software").targetLabel("software").properties("weight").ifNotExist().create()
graph.schema().edgeLabel("define").sourceLabel("software").targetLabel("language").properties("weight").ifNotExist().create()
graph.schema().edgeLabel("implements").sourceLabel("software").targetLabel("software").properties("weight").ifNotExist().create()
graph.schema().edgeLabel("supports").sourceLabel("software").targetLabel("language").properties("weight").ifNotExist().create()

**Comment by cyberpsyche** [comment]
谢谢，又仔细核对了一遍，发现 “graph.schema() "应该改为 "schema"。 再次导入后就不报groovy语法问题了。 但是又有新的问题出现，根据上述schema，导入时报：
vertices has been loaded : 0
ERROR: Failed to load
Exception in thread "main" java.lang.IllegalStateException: The id field can't be empty or null when id strategy is CUSTOMIZE for vertex label 'person'

我尝试着在 vertex_person.csv 文件中加入“id”字段，但不生效，依然报相同错误。望指教如何处理？ 谢谢！

**Comment by javeme** [comment]
@cyberpsyche 这个需要放在与`label`同级的位置：`"id": "id"` (不是放在field_mapping内部)

**Comment by cyberpsyche** [comment]
@javeme 谢谢，已解决问题！
