### ISSUE TITLE
can't parse node correctly

### ISSUE THREAD

**Issue by Catriminal** [hugegraph/hugegraph-loader#130]
请问是什么原因导致loader把顶点id解析成int型，进而导致不能parse顶点呢？
这是我的错误日志：
```
2020-02-06 16:08:06 [main] [INFO ] com.baidu.hugegraph.loader.struct.GraphStruct [] - Checking vertex struct descriptions
2020-02-06 16:08:07 [main] [INFO ] com.baidu.hugegraph.loader.struct.GraphStruct [] - Checking edge struct descriptions
2020-02-06 16:08:08 [main] [INFO ] com.baidu.hugegraph.loader.HugeGraphLoader [] - Start loading vertices
2020-02-06 16:08:08 [main] [INFO ] com.baidu.hugegraph.loader.reader.file.FileReader [] - Opening struct 'VertexStruct(person-b1791530)'
2020-02-06 16:08:08 [main] [INFO ] com.baidu.hugegraph.loader.HugeGraphLoader [] - Start parsing and loading 'VertexStruct(person-b1791530)'
2020-02-06 16:08:08 [main] [ERROR] com.baidu.hugegraph.loader.HugeGraphLoader [] - Parse VERTEX error
com.baidu.hugegraph.loader.exception.ParseException: Failed to convert value 93138929000(class java.lang.String) to Number
	at com.baidu.hugegraph.loader.builder.ElementBuilder.next(ElementBuilder.java:113) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:186) [hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:161) [hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:132) [hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:89) [hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66) [hugegraph-loader-0.10.1.jar:?]
Caused by: java.lang.IllegalArgumentException: Failed to convert value 93138929000(class java.lang.String) to Number
	at com.baidu.hugegraph.loader.util.DataTypeUtil.parseNumber(DataTypeUtil.java:239) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.parseSingleValue(DataTypeUtil.java:115) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.convert(DataTypeUtil.java:65) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.validatePropertyValue(ElementBuilder.java:194) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.addProperties(ElementBuilder.java:173) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:64) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:35) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.next(ElementBuilder.java:110) ~[hugegraph-loader-0.10.1.jar:?]
	... 5 more
Caused by: java.lang.NumberFormatException: For input string: "93138929000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_242]
	at java.lang.Integer.parseInt(Integer.java:583) ~[?:1.8.0_242]
	at java.lang.Integer.valueOf(Integer.java:766) ~[?:1.8.0_242]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.parseNumber(DataTypeUtil.java:225) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.parseSingleValue(DataTypeUtil.java:115) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.convert(DataTypeUtil.java:65) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.validatePropertyValue(ElementBuilder.java:194) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.addProperties(ElementBuilder.java:173) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:64) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:35) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.next(ElementBuilder.java:110) ~[hugegraph-loader-0.10.1.jar:?]
	... 5 more
2020-02-06 16:08:08 [main] [INFO ] com.baidu.hugegraph.loader.executor.LoadContext [] - Create failure logger for struct 'VertexStruct(person-b1791530)'
2020-02-06 16:08:08 [main] [WARN ] com.baidu.hugegraph.loader.failure.FailureLogger [] - The existed file /root/graph-data/struct/current/person-b1791530.parse-error will be overwritten
2020-02-06 16:08:08 [main] [ERROR] com.baidu.hugegraph.loader.HugeGraphLoader [] - ERROR: More than 1 vertices parsing error, stop parsing and waiting all insert tasks finished
```

这是我的schema.groovy：
```
schema.propertyKey("num").asText().ifNotExist().create();

schema.vertexLabel("person").properties("num").primaryKeys("num").ifNotExist().create();
schema.edgeLabel("knows").sourceLabel("person").targetLabel("person").ifNotExist().create();
```
这是我的struct.json
```
{
    "vertices": [
        {
            "label": "person",
            "input": {
                "type": "file",
                "path": "/root/graph-data/node_de.csv",
                "format": "CSV",
                "header": ["node_id"]
            },
            "field_mapping": {
                "node_id": "num"
            }
        }
    ],
    "edges": [
        {
            "label": "knows",
            "source": ["source_id"],
            "target": ["target_id"],
            "input": {
                "type": "file",
                "path": "/root/graph-data/link_ex.csv",
                "format": "CSV",
                "header": ["source_id", "target_id"]
            },
            "field_mapping": {
                "source_id": "num",
                "target_id": "num"
            }
        }
    ]
}  



```

**Comment by Catriminal** [comment]
我把hugegraphserver降到0.9.2版本，问题就没有了。
