### ISSUE TITLE
从Oracle中导入数据报错，而且报错位置是在mysql的jar包中

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph-loader#135]
ERROR: Failed to load
Exception in thread "main" com.baidu.hugegraph.loader.exception.LoadException: Failed to connect database via 'jdbc:oracle:thin:@//192.168.32.197:1521'
	at com.baidu.hugegraph.loader.reader.jdbc.JDBCReader.<init>(JDBCReader.java:47)
	at com.baidu.hugegraph.loader.reader.InputReaderFactory.create(InputReaderFactory.java:39)
	at com.baidu.hugegraph.loader.builder.ElementBuilder.<init>(ElementBuilder.java:71)
	at com.baidu.hugegraph.loader.builder.VertexBuilder.<init>(VertexBuilder.java:41)
	at com.baidu.hugegraph.loader.builder.ElementBuilder.of(ElementBuilder.java:78)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:159)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:132)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:89)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66)
Caused by: java.sql.SQLNonTransientConnectionException: Cannot load connection class because of underlying exception: com.mysql.cj.core.exceptions.WrongArgumentException: Malformed database URL, failed to parse the main URL sections.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:526)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:489)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:72)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:124)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:224)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.baidu.hugegraph.loader.reader.jdbc.RowFetcher.connect(RowFetcher.java:75)
	at com.baidu.hugegraph.loader.reader.jdbc.RowFetcher.<init>(RowFetcher.java:55)
	at com.baidu.hugegraph.loader.reader.jdbc.JDBCReader.<init>(JDBCReader.java:44)
	... 8 more

我的配置如下
{
    "vertices":[
        {
            "label":"sysUser",
            "update_strategies":{
                "id":"OVERRIDE",
                "name":"OVERRIDE",
                "code":"OVERRIDE",
                "login_name":"OVERRIDE",
                "sex":"OVERRIDE",
                "email":"OVERRIDE"
            },
            "input":{
                "type":"jdbc",
                "vendor":"Oracle",
                "driver":"oracle.jdbc.driver.OracleDriver",
                "url":"jdbc:oracle:thin:@//xxx.xxx.xxx.xxx:1521",
                "database":"orcl",
                "table":"xxx",
                "username":"xxxxxxxxx",
                "password":"xxxxxxxxxx"
            },
            "null_values":[
                "NULL",
                "null",
                ""
            ]
        },
        {
            "label":"org",
            "update_strategies":{
                "id":"OVERRIDE",
                "name":"OVERRIDE",
                "code":"OVERRIDE"
            },
            "input":{
                "type":"jdbc",
                "vendor":"Oracle",
                "driver":"oracle.jdbc.driver.OracleDriver",
                "url":"jdbc:oracle:thin:@//xxx.xxx.xxx.xxx:1521",
                "database":"orcl",
                "table":"xxx",
                "username":"xxxxxxxxx",
                "password":"xxxxxxxxx"
            },
            "null_values":[
                "NULL",
                "null",
                ""
            ]
        },
	......
    ],
    "edges":[
        ......
    ]
}

请问这是怎么回事？

**Comment by Linary** [comment]
这似乎是MySQL connector/Java的一个BUG
https://bugs.mysql.com/bug.php?id=87600

**Comment by Linary** [comment]
@I-DO-NOT-KNOW 你可以从lib目录下把mysql-connector-java-6.0.6.jar剪切出去试试能不能正常走oracle的流程。
