### ISSUE TITLE
从CSV中导入，有类型转换错误

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph-loader#145]
当导入值对应的是空字符串时，报有类型转换错误
报错如下：
Caused by: java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:1.8.0_231]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_231]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_231]
	at java.lang.Double.valueOf(Double.java:502) ~[?:1.8.0_231]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.parseNumber(DataTypeUtil.java:230) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.parseSingleValue(DataTypeUtil.java:115) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.convert(DataTypeUtil.java:65) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.validatePropertyValue(ElementBuilder.java:194) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.addProperties(ElementBuilder.java:173) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:64) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:35) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.next(ElementBuilder.java:110) ~[hugegraph-loader-0.10.0.jar:?]
	... 5 more

Caused by: java.lang.IllegalArgumentException: Unparseable date: "", expect format: yyyy-MM-dd HH:mm:ss
	at com.baidu.hugegraph.loader.util.DataTypeUtil.parseDate(DataTypeUtil.java:262) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.parseSingleValue(DataTypeUtil.java:123) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.convert(DataTypeUtil.java:65) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.validatePropertyValue(ElementBuilder.java:194) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.addProperties(ElementBuilder.java:173) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:64) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:35) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.next(ElementBuilder.java:110) ~[hugegraph-loader-0.10.0.jar:?]
	... 5 more

**Comment by Linary** [comment]
```
Caused by: java.lang.IllegalArgumentException: Unparseable date: "", expect format: yyyy-MM-dd HH:mm:ss
```
你可以把这个日期属性在元数据中设置为可空的，这样就不会导入空值了

**Comment by Linary** [comment]
可以参考一下这个issue https://github.com/hugegraph/hugegraph-loader/issues/144
