### ISSUE TITLE
The example  on official website can't be loaded

### ISSUE THREAD

**Issue by wangzhanxd** [hugegraph/hugegraph-loader#149]
bin/hugegraph-loader -h 192.168.8.126 -g hugegraph -f example/file/struct.json -s example/file/schema.groovy

ERROR: Failed to load
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy53.create(Unknown Source)
        at com.baidu.hugegraph.structure.schema.SchemaBuilder$create.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at Script1.run(Script1.groovy:14)
        at com.baidu.hugegraph.loader.executor.GroovyExecutor.execute(GroovyExecutor.java:58)
        at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:118)
        at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:85)
        at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.baidu.hugegraph.structure.schema.BuilderProxy.invoke(BuilderProxy.java:56)
        ... 10 more
Caused by: class java.lang.IllegalArgumentException: Not all index fields '[city]' are contained in schema properties '[name, age, addr, weight]'
        at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
        at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
        at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:156)
        at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:133)
        at com.baidu.hugegraph.api.schema.IndexLabelAPI.create(IndexLabelAPI.java:51)
        at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:187)
        at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:182)
        at com.baidu.hugegraph.structure.schema.IndexLabel$BuilderImpl.create(IndexLabel.java:133)
        at com.baidu.hugegraph.structure.schema.IndexLabel$BuilderImpl.create(IndexLabel.java:116)
        ... 15 more

**Comment by javeme** [comment]
> IllegalArgumentException: Not all index fields '[city]' are contained in schema properties '[name, age, addr, weight]'

@wangzhanxd According to the error message, it seems that the schema definition is wrong, if you have changed property key from `city` to `addr`, please also update the index label definition:
`schema.indexLabel ("personByCity"). onV ("person"). by ("city"). secondary ().. create ();`
=>
`schema.indexLabel ("personByAddr"). onV ("person"). by ("addr"). secondary (). create ();`

**Comment by wangzhanxd** [comment]
Thank you very much
