### ISSUE TITLE
load from mysql error，struct.json 和schema 都是用example 中的

### ISSUE THREAD

**Issue by sachinly** [hugegraph/hugegraph-loader#152]
使用的命令：
`./bin/hugegraph-loader -g hugegraph -s example/mysql/schema.groovy -f example/mysql/struct.json`                           
mysql 是自己搭建的，是正常的。
版本：hugegraph-loader-0.10.0

错误终端信息：
Exception in thread "main" com.baidu.hugegraph.rest.SerializeException: Failed to deserialize json
	at com.baidu.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:70)
	at com.baidu.hugegraph.loader.struct.GraphStruct.of(GraphStruct.java:67)
	at com.baidu.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:71)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:65)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid json, expect 'vendor' in '{"driver":"com.mysql.cj.jdbc.Driver","url":"jdbc:mysql://192.168.7.5:3306","database":"example","table":"person","username":"root","password":"xxxxxxx","batch_size":500}' (through reference chain: com.baidu.hugegraph.loader.struct.GraphStruct["vertices"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:189)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:262)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3564)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2580)
	at com.baidu.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:68)
	... 3 more
Caused by: com.baidu.hugegraph.loader.serializer.DeserializeException: Invalid json, expect 'vendor' in '{"driver":"com.mysql.cj.jdbc.Driver","url":"jdbc:mysql://192.168.7.5:3306","database":"example","table":"person","username":"root","password":"xxxxx","batch_size":500}'
	at com.baidu.hugegraph.loader.serializer.DeserializeException.expectField(DeserializeException.java:41)
	at com.baidu.hugegraph.loader.serializer.InputSourceDeser.getNode(InputSourceDeser.java:80)
	at com.baidu.hugegraph.loader.serializer.InputSourceDeser.readInputSource(InputSourceDeser.java:65)
	at com.baidu.hugegraph.loader.serializer.InputSourceDeser.deserialize(InputSourceDeser.java:48)
	at com.baidu.hugegraph.loader.serializer.InputSourceDeser.deserialize(InputSourceDeser.java:38)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:416)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)

**Comment by Linary** [comment]
在映射文件struct.json中增加一个"vendor": "mysql"。
