### ISSUE TITLE
如何从pg中往hugegraph导入date类型

### ISSUE THREAD

**Issue by wangchao213** [hugegraph/hugegraph-loader#154]
java.lang.IllegalStateException: Only accept FileSource when convert String value to Date, but got 'com.baidu.hugegraph.loader.source.jdbc.JDBCSource'
	at com.google.common.base.Preconditions.checkState(Preconditions.java:172) ~[guava-11.0.2.jar:?]
	at com.baidu.hugegraph.util.E.checkState(E.java:68) ~[hugegraph-common-1.6.11.jar:1.6.11.0]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.parseSingleValue(DataTypeUtil.java:119) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.util.DataTypeUtil.convert(DataTypeUtil.java:65) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.validatePropertyValue(ElementBuilder.java:194) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.addProperties(ElementBuilder.java:173) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:64) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:35) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.next(ElementBuilder.java:110) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:186) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:161) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:132) ~[hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:89) [hugegraph-loader-0.10.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66) [hugegraph-loader-0.10.1.jar:?]
2020-04-30 10:28:21 [main] [INFO ] com.baidu.hugegraph.loader.HugeGraphLoader [] - Stop loading then shutdown HugeGraphLoader
2020-04-30 10:28:21 [main] [INFO ] com.baidu.hugegraph.loader.task.TaskManager [] - Waiting for the insert tasks of vertices finish
2020-04-30 10:28:21 [main] [INFO ] com.baidu.hugegraph.loader.task.TaskManager [] - The batch-mode tasks finished
2020-04-30 10:28:21 [main] [INFO ] com.baidu.hugegraph.loader.task.TaskManager [] - The single-mode tasks finished
2020-04-30 10:28:21 [main] [DEBUG] com.baidu.hugegraph.loader.task.TaskManager [] - Ready to shutdown batch-mode tasks executor
2020-04-30 10:28:21 [main] [DEBUG] com.baidu.hugegraph.loader.task.TaskManager [] - Ready to shutdown single-mode tasks executor
2020-04-30 10:28:21 [Thread-1] [INFO ] com.baidu.hugegraph.loader.HugeGraphLoader [] - Stop loading then shutdown HugeGraphLoader
2020-04-30 10:28:21 [Thread-1] [DEBUG] com.baidu.hugegraph.loader.task.TaskManager [] - Ready to shutdown batch-mode tasks executor
2020-04-30 10:28:21 [Thread-1] [DEBUG] com.baidu.hugegraph.loader.task.TaskManager [] - Ready to shutdown single-mode tasks executor

**Comment by javeme** [comment]
@wangchao213 目前还不支持，后续会进行增强。

**Comment by gitgoready** [comment]
现在还没支持吗？

**Comment by shichen00056** [comment]
https://github.com/apache/incubator-hugegraph-toolchain/blob/4b89c5d8d8a36d6361987d0b3ca248370793fccf/hugegraph-loader/src/main/java/org/apache/hugegraph/loader/util/DataTypeUtil.java#L140
这里是不是应该去掉这个验证了，有这个验证，只要数据类型包括Date类型，就只能加载filesource 类的数据源，其他类型的数据源加载都会在这个验证这里异常
