### ISSUE TITLE
vertex定义联合主键，使用hugegraph-loader导入数据，报错

### ISSUE THREAD

**Issue by azhegit** [hugegraph/hugegraph-loader#17]
#### 离线批量导入节点、边。
但是发现使用过程中遇见问题，通过只导入顶点，定位到问题出现原因是在联合主键数据导入失败。（schema是创建好了，只是数据导入不进去，通过java-api可以在已经建好的schema中写入联合主键的节点）

#### 使用loader导入数据失败：
Vertices has been imported:Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at com.baidu.hugegraph.loader.parser.VertexParser.assignIdIfNeed(VertexParser.java:93)
	at com.baidu.hugegraph.loader.parser.VertexParser.parse(VertexParser.java:55)
	at com.baidu.hugegraph.loader.parser.VertexParser.parse(VertexParser.java:33)
	at com.baidu.hugegraph.loader.parser.ElementParser.next(ElementParser.java:80)
	at com.baidu.hugegraph.loader.HugeGraphLoader.loadVertex(HugeGraphLoader.java:187)
	at com.baidu.hugegraph.loader.HugeGraphLoader.loadVertices(HugeGraphLoader.java:170)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:111)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:68)
#### schema建好：
![image](https://user-images.githubusercontent.com/39914304/48604252-35280380-e9b4-11e8-8747-cad2b0a5ad8f.png)

#### java-api写入数据成功：
![image](https://user-images.githubusercontent.com/39914304/48604142-c6e34100-e9b3-11e8-81e8-2bfee62b2262.png)

### 复现：
1. 编写schema.groovy
```groovy
// Define schema
schema.propertyKey("name").asText().ifNotExist().create();
schema.propertyKey("age").asInt().ifNotExist().create();
schema.propertyKey("city").asText().ifNotExist().create();
schema.propertyKey("weight").asDouble().ifNotExist().create();
schema.propertyKey("date").asText().ifNotExist().create();

schema.vertexLabel("person")
                .properties("name", "age", "city")
                .primaryKeys("name","city")
                .ifNotExist()
                .create();

schema.edgeLabel("knows").sourceLabel("person").targetLabel("person").properties("date", "weight").ifNotExist().create();
```
2.编写struct.json
```
{
  "vertices": [
    {
      "label": "person",
      "input": {
        "type": "file",
        "path": "vertex_person.csv",
        "format": "CSV",
        "header": ["name", "age", "city"],
        "charset": "UTF-8"
      },
      "mapping": {
        "name": "name",
        "age": "age",
        "city": "city"
      }
    }
  ]

}
```
3.编写顶点数据：vertex_person.csv
```cs
xiaoming,29,Beijing
lilei,27,Hongkong
lilei,32,Beijing
hanmeimei,35,Shanghai
"zhangsan",26,"Wu,han"
```
4.编写边数据：edge_knows.json
```json
{"source_name": "lilei", "target_name": "hanmeimei","date": "20130220", "weight": 1.0}
```
5.执行命令：`hugegraph-loader -g hugegraph -f struct.json -s schema.groovy`

**Comment by Linary** [comment]
@azhegit 非常感谢您的反馈，这确实是Loader的一个BUG，我们会马上修复

**Comment by azhegit** [comment]
> @azhegit 非常感谢您的反馈，这确实是Loader的一个BUG，我们会马上修复

嗯，感谢，我会继续关注，修复之后，希望有联合主键导入的struct例子
