### ISSUE TITLE
导入时hbase作为后端存储导入速度很慢，有没有可以提升的方案？

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph-loader#184]
loader在对接hbase的存储后端时能达到多少的写入速度？
我们测试了5千万顶点的数据导入非常耗时（batch_sizes设置的5000），而且server的日志里面不断打印异常，如下图。这个有什么好的方法可以提升写入速度嘛？（边的导入不check顶点反而要比顶点快很多）

 hugegraph-loader.log
```
2020-11-19 10:39:04 [main] [INFO ] c.b.h.l.HugeGraphLoader [] - Start loading
2020-11-19 10:39:06 [main] [WARN ] o.a.h.u.NativeCodeLoader [] - Unable to load native-hadoop library for your platform... using builtin-java classes where ap                                                                                                                                plicable
2020-11-19 10:39:07 [main] [INFO ] c.b.h.l.HugeGraphLoader [] - Start parsing and loading 'input-mapping(id=1)'
2020-11-19 10:40:30 [batch-worker-20] [ERROR] c.b.h.l.t.TaskManager [] - server exception: The rest server is too busy to write
2020-11-19 10:40:30 [batch-worker-21] [ERROR] c.b.h.l.t.TaskManager [] - server exception: The rest server is too busy to write
2020-11-19 10:40:30 [batch-worker-22] [ERROR] c.b.h.l.t.TaskManager [] - server exception: The rest server is too busy to write
2020-11-19 10:40:30 [batch-worker-23] [ERROR] c.b.h.l.t.TaskManager [] - server exception: The rest server is too busy to write
2020-11-19 10:40:31 [batch-worker-24] [ERROR] c.b.h.l.t.TaskManager [] - server exception: The rest server is too busy to write
2020-11-19 12:10:20 [batch-worker-12] [INFO ] c.b.h.l.u.Printer [] - vertices has been loaded: 10000000, average load rate: 1826/s
2020-11-19 13:33:57 [batch-worker-19] [INFO ] c.b.h.l.u.Printer [] - vertices has been loaded: 20000000, average load rate: 1906/s

```

hugegraph-server.log

```
2020-11-19 14:41:59 78075405 [grizzly-http-server-47] [INFO ] org.apache.hadoop.hbase.client.AsyncRequestFutureImpl [] - #3, waiting for 1212  actions to finish on table: hugegraph:g_v
十一月 19, 2020 2:41:59 下午 org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
严重: An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: java.io.IOException: Connection is closed
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Connection is closed
        at org.glassfish.grizzly.nio.NIOConnection.assertOpen(NIOConnection.java:445)
        at org.glassfish.grizzly.http.io.OutputBuffer.write(OutputBuffer.java:677)
        at org.glassfish.grizzly.http.server.NIOOutputStreamImpl.write(NIOOutputStreamImpl.java:83)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2033)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:454)
        at com.fasterxml.jackson.databind.ser.impl.IndexedStringListSerializer.serializeContents(IndexedStringListSerializer.java:121)
        at com.fasterxml.jackson.databind.ser.impl.IndexedStringListSerializer.serialize(IndexedStringListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedStringListSerializer.serialize(IndexedStringListSerializer.java:21)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:416)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1416)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:940)
        at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:618)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)
        ... 19 more
Caused by: java.io.IOException: 断开的管道
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.glassfish.grizzly.nio.transport.TCPNIOUtils.flushByteBuffer(TCPNIOUtils.java:149)
        at org.glassfish.grizzly.nio.transport.TCPNIOUtils.writeCompositeBuffer(TCPNIOUtils.java:86)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:129)
        at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:106)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:260)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:169)
        at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:71)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleWrite(TCPNIOTransportFilter.java:126)
        at org.glassfish.grizzly.filterchain.TransportFilter.handleWrite(TransportFilter.java:191)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$8.execute(ExecutorResolver.java:111)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:890)
        at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:858)
        at org.glassfish.grizzly.http.io.OutputBuffer.flushBuffer(OutputBuffer.java:1059)
        at org.glassfish.grizzly.http.io.OutputBuffer.write(OutputBuffer.java:709)
        at org.glassfish.grizzly.http.server.NIOOutputStreamImpl.write(NIOOutputStreamImpl.java:83)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2033)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:459)
        ... 32 more

2020-11-19 14:42:00 78075483 [grizzly-http-server-22] [INFO ] org.apache.hadoop.hbase.client.AsyncRequestFutureImpl [] - #3, waiting for 1148  actions to finish on table: hugegraph:g_v

````

**Comment by tmljob** [comment]
[arthas-火焰图.zip](https://github.com/hugegraph/hugegraph-loader/files/5565642/arthas-.zip)

**Comment by Linary** [comment]
关闭schema的labelIndex试试
```
schema.vertexLabel("person")
             .properties("name", "age", "city")
             .primaryKeys("name")
             .nullableKeys("city")
             .enableLabelIndex(false)
             .create();
```

**Comment by javeme** [comment]
> loader在对接hbase的存储后端时能达到多少的写入速度？

与集群规模和磁盘类型有关，正常情况下，普通机械盘一般在5节点集群规模下3~5万/秒，SSD盘可达到10~30万/秒。

**Comment by imbajin** [comment]
一点个人心得, 仅供参考: 
1. 如果不使用 `hasLabel()` 查询, 或者场景很少, 参考作者说的设置关闭**所有点边**的labelIndex, 不仅少写一张索引表提升性能, 也节省不少存储空间.
2. 如果点边总数小于10亿 (甚至可能50~100亿). 个人觉得没必要用hbase, 不如用单台高性能的机器, 然后优化一下rocksdb配置, 
3. 如果使用 hbase 集群, rs 数目在7台以上, 建议预分配region(目前只能手动, 可参考server类似issue), 现在默认是1个region, 前中期请求都打到了有限的几台机器, 会受到很大影响.
4. 但是就算只有一台 rs, 你的1-2k的 **覆盖写** 导入速度也是特别慢的, 你导入数据有开启 **更新策略** 么? 如果没有那肯定是**不正常**的, 我很早实测单机hbase+hdd盘, 也可以有接近 **5~10万/s** 的点边写入速度.
5. 你可以看看 server 负载和 hbase 那边的负载, hbase应该**很闲**才对, 看看是谁成了瓶颈, 图server负载高的话, 看看是配置太低? 还是在忙什么, 然后 `Arthas` 看看批量写入那的平均耗时, 然后看看调用 hbase-client put的平均耗时.

**Comment by Linary** [comment]
感谢 @imbajin 的精彩解答

**Comment by tmljob** [comment]
导入数据时没有设置更新策略；
导入开始，日志会报大量“ server exception: The rest server is too busy to write”，再然后“Batch insert VERTEX error, try single insert”，单个插入还会报“The rest server is too busy to write”，后面超过500个失败，程序就终止了。

1、”The rest server is too busy to write“这个异常我看是writingThreads > maxWriteThreads才抛出的。但是，我hugegraph-server写入的线程是43（maxWriteThreads），loader的线程数通过--batch-insert-threads 28 设置为28了，为什么还是抛这个异常报错。loader的写入线程数是通过这个参数控制的嘛？

2、在另外1套环境，跑同样5kw的数据，速度可以达到1.5w/s，也不会报“ server exception: The rest server is too busy to write”错误。这两套环境也没发现有大的差异，甚至1.5w/s的环境，内存还没有另外一套大，想不通为啥导入速度差别这么大。

**Comment by Linary** [comment]
1. 你 server 的最大写线程数是用哪个参数设置的？batch.max_write_ratio 还是 batch.max_write_threads？另外 loader 的线程数是批量写线程数（28）加上单条写线程数（默认为8），加起来 36 < 43 应该是不会触发那个异常的，你再检查下是不是那个参数用错了；
2. 检查下是不是有别的什么进程，比如跑了两个loader，起了两个server这种。

**Comment by tmljob** [comment]
经过定位，发现是这个大数据集群环境一个datanode节点的磁盘空间快满了，接近98%，导致写入的速度很慢。因这个环境有多个业务在用，把图数据库重装清空以前导入的数据，这个节点磁盘占用率下降到74%，然后在导入速度就正常了。
