### ISSUE TITLE
loader的一些问题

### ISSUE THREAD

**Issue by FANGOD** [hugegraph/hugegraph-loader#208]
1. laoder 0.11.2 导入hdfs json 个别`边`报#### PARSE ERROR: The list_format must be set when parse list or set values , 话说json list中没有别的分隔符吧? 大部分边都有set, 只有3条边的解析失败, 其他的边正常导入了

## env
```bash
 /home/netlab/xgraph-loader-0.11.2.0/bin/hugegraph-loader.sh

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```
## mapping
```JavaScript
 96     {
 97       "label": "fu",
 98       "source": [
 99         "m"
100       ],
101       "target": [
102         "ur"
103       ],
104       "update_strategies": {
105         "pa": "UNION",
106         "po": "UNION",
107         "pr": "UNION",
108         "bo": "UNION",
109         "me": "UNION",
110         "sr": "UNION",
111         "fi": "SMALLER",
112         "la": "BIGGER",
113         "co": "SUM"
114       },
115       "input": {
116         "type": "hdfs",
117         "path": "/20210428/fu",
118         "core_site_path": "/usr/bin/hadoop/software/hadoop/etc/hadoop/core-site.xml",
119         "hdfs_site_path": "/usr/bin/hadoop/software/hadoop/etc/hadoop/hdfs-site.xml",
120         "format": "JSON"
121       }
122     },
```
## data
```bash
 #### PARSE ERROR: The list_format must be set when parse list or set values
{"sr": ["sa"], "pr": "hp", "fi": "2020-10-28 21:39:49", "m": "9993619a2a80c56626eb66f677bd5c89", "ur": "4822b7f4f04a3b9837fa1e89af85435401a82d0446f6f88e515d5b318e9d87ff", "po": "8080", "la": "2020-10-28 21:39:49"}
{"sr": ["mm"], "pr": "hp", "fi": "2019-07-12 00:43:53", "m": "9993715afc6201c83bdc01e3471df6b5", "ur": "0481e228fd79b6c64decaa42607554b36791c1d00332d3249d9d8ab9c6d7f751", "po": "80", "la": "2019-07-12 00:43:53"}
{"sr": ["sa"], "pr": "hp", "fi": "2020-11-24 11:53:22", "m": "999376a2d15dcead814e10b2d6056476", "ur": "f56385cba67e0dc2aec195a2fda398131242d02db3ebb4dcaebaba58ebd9b3e3", "po": "80", "la": "2020-11-24 11:53:22"}
```
## log
```java
10533 2021-04-30 16:56:45 [main] [ERROR] c.b.h.l.t.ParseTaskBuilder [] - Parse EDGE error
10534 com.baidu.hugegraph.loader.exception.ParseException: The list_format must be set when parse list or set values
10535     at com.baidu.hugegraph.loader.task.ParseTaskBuilder.lambda$buildTask$0(ParseTaskBuilder.java:113) ~[xgraph-loader-0.11.1.jar:?]
10536     at com.baidu.hugegraph.loader.task.ParseTaskBuilder$ParseTask.get(ParseTaskBuilder.java:152) [xgraph-loader-0.11.1.jar:?]
10537     at com.baidu.hugegraph.loader.HugeGraphLoader.executeParseTask(HugeGraphLoader.java:265) [xgraph-loader-0.11.1.jar:?]
10538     at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:244) [xgraph-loader-0.11.1.jar:?]
10539     at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:197) [xgraph-loader-0.11.1.jar:?]
10540     at com.baidu.hugegraph.loader.HugeGraphLoader.loadInputs(HugeGraphLoader.java:170) [xgraph-loader-0.11.1.jar:?]
10541     at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:108) [xgraph-loader-0.11.1.jar:?]
10542     at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:71) [xgraph-loader-0.11.1.jar:?]
10543 Caused by: java.lang.IllegalArgumentException: The list_format must be set when parse list or set values
10544     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:164) ~[guava-29.0-jre.jar:?]
10545     at com.baidu.hugegraph.util.E.checkArgumentNotNull(E.java:62) ~[hugegraph-common-1.8.4.jar:1.8.4.0]
10546     at com.baidu.hugegraph.loader.util.DataTypeUtil.split(DataTypeUtil.java:286) ~[xgraph-loader-0.11.1.jar:?]
10547     at com.baidu.hugegraph.loader.util.DataTypeUtil.parseMultiValues(DataTypeUtil.java:175) ~[xgraph-loader-0.11.1.jar:?]
10548     at com.baidu.hugegraph.loader.util.DataTypeUtil.convert(DataTypeUtil.java:72) ~[xgraph-loader-0.11.1.jar:?]
10549     at com.baidu.hugegraph.loader.builder.ElementBuilder.convertPropertyValue(ElementBuilder.java:213) ~[xgraph-loader-0.11.1.jar:?]
10550     at com.baidu.hugegraph.loader.builder.ElementBuilder.addProperties(ElementBuilder.java:151) ~[xgraph-loader-0.11.1.jar:?]
10551     at com.baidu.hugegraph.loader.builder.EdgeBuilder.build(EdgeBuilder.java:102) ~[xgraph-loader-0.11.1.jar:?]
10552     at com.baidu.hugegraph.loader.task.ParseTaskBuilder.lambda$buildTask$0(ParseTaskBuilder.java:93) ~[xgraph-loader-0.11.1.jar:?]
10553     ... 7 more
```
2. 然后mapping中指定了分割符, 问题1没了, 又出现
```java
2021-05-06 15:23:51 [main] [ERROR] c.b.h.l.u.Printer [] - Failed to start loading, cause: Invalid mapping file 'run_mapping.json'
com.baidu.hugegraph.loader.exception.LoadException: Invalid mapping file 'run_mapping.json'
        at com.baidu.hugegraph.loader.mapping.LoadMapping.of(LoadMapping.java:73) ~[xgraph-loader-0.11.1.jar:?]
        at com.baidu.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:79) ~[xgraph-loader-0.11.1.jar:?]
        at com.baidu.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:75) ~[xgraph-loader-0.11.1.jar:?]
        at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66) [xgraph-loader-0.11.1.jar:?]
Caused by: java.lang.IllegalArgumentException: The delimiters of fields(,) and list elements(,) can't be the same
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:164) ~[guava-29.0-jre.jar:?]
        at com.baidu.hugegraph.util.E.checkArgument(E.java:56) ~[hugegraph-common-1.8.4.jar:1.8.4.0]
        at com.baidu.hugegraph.loader.source.file.FileSource.check(FileSource.java:102) ~[xgraph-loader-0.11.1.jar:?]
        at com.baidu.hugegraph.loader.source.hdfs.HDFSSource.check(HDFSSource.java:49) ~[xgraph-loader-0.11.1.jar:?]
        at com.baidu.hugegraph.loader.mapping.InputStruct.check(InputStruct.java:60) ~[xgraph-loader-0.11.1.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
        at com.baidu.hugegraph.loader.mapping.LoadMapping.check(LoadMapping.java:93) ~[xgraph-loader-0.11.1.jar:?]
        at com.baidu.hugegraph.loader.mapping.LoadMapping.of(LoadMapping.java:71) ~[xgraph-loader-0.11.1.jar:?]
        ... 3 more


2021-05-07 20:18:56 [main] [INFO ] c.b.h.l.HugeGraphLoader [] - Start parsing and loading 'input-mapping(id=9)'
2021-05-07 20:40:33 [main] [ERROR] c.b.h.l.u.Printer [] - Failed to load, cause: 6
java.lang.ArrayIndexOutOfBoundsException: 6
	at com.baidu.hugegraph.loader.builder.ElementBuilder$VertexPkKVPairs.extractFromEdge(ElementBuilder.java:510) ~[xgraph-loader-0.11.1.jar:?]
	at com.baidu.hugegraph.loader.builder.EdgeBuilder.build(EdgeBuilder.java:76) ~[xgraph-loader-0.11.1.jar:?]
	at com.baidu.hugegraph.loader.task.ParseTaskBuilder.lambda$buildTask$0(ParseTaskBuilder.java:93) ~[xgraph-loader-0.11.1.jar:?]
	at com.baidu.hugegraph.loader.task.ParseTaskBuilder$ParseTask.get(ParseTaskBuilder.java:152) ~[xgraph-loader-0.11.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.executeParseTask(HugeGraphLoader.java:265) ~[xgraph-loader-0.11.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:244) ~[xgraph-loader-0.11.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:197) ~[xgraph-loader-0.11.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.loadInputs(HugeGraphLoader.java:170) ~[xgraph-loader-0.11.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:108) [xgraph-loader-0.11.1.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:71) [xgraph-loader-0.11.1.jar:?]
2021-05-07 20:40:33 [main] [INFO ] c.b.h.l.HugeGraphLoader [] - Stop loading then shutdown HugeGraphLoader

```
说是分隔符不能一样, 我又去掉了分隔符会回到问题1上, file的情况下使用json没问题, 分隔符貌似不会生效,hdfs的情况下不可以使用逗号分隔符
3. 但是一定要导完了或者切掉了才知道loader在导,导的过程中没有实时刷新的显示了,所以我一度以为代码卡在那里了
4. please 新的loader mapping v2.0给更多或者更清晰的例子,现存的看起来很是困惑

Thanks~

**Comment by imbajin** [comment]
最主要的点, 就是先提供一下数据样式, 不然可能有理解上的偏差, 不管是 json/text/csv 还是其他格式, 都需要给一下你报错的地方的数据例子 (具体内容你可以模糊一下)

然后参考更多的例子, 可以看一下 loader 源码的[测试代码](https://github.com/hugegraph/hugegraph-loader/blob/master/src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java)部分, 关于不同文件的分隔符, 或者 `list/set` 解析都有对应简单测试. (然后新旧的映射文件, 有一个脚本可以直接执行, 你如果用旧版写, 也可以直接转换)

关于后续的文档部分, 的确需要再优化一下方便理解和适应, 你可以重新把问题数据补充一下, 看看哪最容易误解.

**Comment by FANGOD** [comment]
> 最主要的点, 就是先提供一下数据样式, 不然可能有理解上的偏差, 不管是 json/text/csv 还是其他格式, 都需要给一下你报错的地方的数据例子 (具体内容你可以模糊一下)
> 
> 然后参考更多的例子, 可以看一下 loader 源码的[测试代码](https://github.com/hugegraph/hugegraph-loader/blob/master/src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java)部分, 关于不同文件的分隔符, 或者 `list/set` 解析都有对应简单测试. (然后新旧的映射文件, 有一个脚本可以直接执行, 你如果用旧版写, 也可以直接转换)
> 
> 关于后续的文档部分, 的确需要再优化一下方便理解和适应, 你可以重新把问题数据补充一下, 看看哪最容易误解.

好的, 我后面会添加更多细节

**Comment by FANGOD** [comment]
Up

**Comment by FANGOD** [comment]
> 因为你说的内容有点多, 我从头到尾认真看了几遍, 还有几个关键点需要确认一下:
> 
> 1. 看起来你的问题就是集中在 `list/set` 的属性偶尔会**没有被正常解析**上, 你觉得可能是 `HDFS` 或者 不同格式导致的, 这个姑且可以先放一下
> 2. 但是从你提供的`struct.json`文件里, 有个可配 `list/set` 格式配置`list_format`参数缺失了, 它不配就使用默认值, 导致不符合预期的报错产生, 这是我推测的原因
> 3. `list_format` 具体配置参考 [loader文档](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html), 它提供了三个参数控制, 绝大部分**分隔符**类冲突的问题都可以通过配置它解决
> 4. 不过文档里没有提供太详细的默认值, 设置方式说明, 但你可以从[ListFormat源代码](https://github.com/hugegraph/hugegraph-loader/blob/master/src/main/java/com/baidu/hugegraph/loader/source/file/ListFormat.java)这里找到参考, 然后尝试配置一下它看看, 是不是能解决, 还有一个办法就是, 你把你报错对应的**几条数据**, 用 text 的方式写几行, 然后试试配上 `list_format` 是否能解析,
> 
> > 但是一定要导完了或者切掉了才知道loader在导,导的过程中没有实时刷新的显示了,所以我一度以为代码卡在那里了
> > 这个是啥意思, 是说 lodaer 的动态加载导入点边数停滞了么? (那应该是不正常的, 并不会等导完才知道)
> 
> > please 新的loader mapping v2.0给更多或者更清晰的例子,现存的看起来很是困惑
> > lodaer 目录的`./bin/`下有个转换至 v2.0 的工具, 然后具体的完整例子也是参考刚的 loader 文档. 有具体不理解的可以说
> 
> 期待后续回复, 感谢提供具体的信息方便定位问题.



> 因为你说的内容有点多, 我从头到尾认真看了几遍, 还有几个关键点需要确认一下:
> 
> 1. 看起来你的问题就是集中在 `list/set` 的属性偶尔会**没有被正常解析**上, 你觉得可能是 `HDFS` 或者 不同格式导致的, 这个姑且可以先放一下
> 2. 但是从你提供的`struct.json`文件里, 有个可配 `list/set` 格式配置`list_format`参数缺失了, 它不配就使用默认值, 导致不符合预期的报错产生, 这是我推测的原因
> 3. `list_format` 具体配置参考 [loader文档](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html), 它提供了三个参数控制, 绝大部分**分隔符**类冲突的问题都可以通过配置它解决
> 4. 不过文档里没有提供太详细的默认值, 设置方式说明, 但你可以从[ListFormat源代码](https://github.com/hugegraph/hugegraph-loader/blob/master/src/main/java/com/baidu/hugegraph/loader/source/file/ListFormat.java)这里找到参考, 然后尝试配置一下它看看, 是不是能解决, 还有一个办法就是, 你把你报错对应的**几条数据**, 用 text 的方式写几行, 然后试试配上 `list_format` 是否能解析,
> 
> > 但是一定要导完了或者切掉了才知道loader在导,导的过程中没有实时刷新的显示了,所以我一度以为代码卡在那里了
> > 这个是啥意思, 是说 lodaer 的动态加载导入点边数停滞了么? (那应该是不正常的, 并不会等导完才知道)
> 
> > please 新的loader mapping v2.0给更多或者更清晰的例子,现存的看起来很是困惑
> > lodaer 目录的`./bin/`下有个转换至 v2.0 的工具, 然后具体的完整例子也是参考刚的 loader 文档. 有具体不理解的可以说
> 
> 期待后续回复, 感谢提供具体的信息方便定位问题.

thanks ~
&这里可能有一部分源码我这边的版本有更新  所以可能问题不一定是这边的

**Comment by imbajin** [comment]
Maybe fixed by #211 , close it now
