### ISSUE TITLE
[Bug] Failed to load, cause: Failed to deserialize: "property_key"

### ISSUE THREAD

**Issue by javeme** [hugegraph/hugegraph-loader#248]
### Before submit

- [X] 我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Loader-Issues](https://github.com/hugegraph/hugegraph-loader/issues) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Loader Version: v0.12.0
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

```java
2022-04-02 17:44:59 [main] [ERROR] c.b.h.l.u.Printer [] - Failed to load, cause: Failed to deserialize: {"property_key": {"id":1,"name":"id","data_type":"LONG","cardinality":"SINGLE","aggregate_type":"NONE","write_type":"OLTP","properties":[],"status":"CREATED","user_data":{"~create_time":"2022-04-02 17:44:59.867"}}, "task_id": 0}
com.baidu.hugegraph.rest.SerializeException: Failed to deserialize: {"property_key": {"id":1,"name":"id","data_type":"LONG","cardinality":"SINGLE","aggregate_type":"NONE","write_type":"OLTP","properties":[],"status":"CREATED","user_data":{"~create_time":"2022-04-02 17:44:59.867"}}, "task_id": 0}
	at com.baidu.hugegraph.rest.RestResult.readObject(RestResult.java:64) ~[hugegraph-common-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.api.schema.PropertyKeyAPI.create(PropertyKeyAPI.java:52) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.SchemaManager.addPropertyKey(SchemaManager.java:89) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.SchemaManager.addPropertyKey(SchemaManager.java:84) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.structure.schema.PropertyKey$BuilderImpl.create(PropertyKey.java:158) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.structure.schema.PropertyKey$BuilderImpl.create(PropertyKey.java:141) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.baidu.hugegraph.structure.schema.BuilderProxy.invoke(BuilderProxy.java:56) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.sun.proxy.$Proxy49.create(Unknown Source) ~[?:?]
	at com.baidu.hugegraph.structure.schema.SchemaBuilder$create.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[groovy-all-2.4.6.jar:2.4.6]
	at Script1.run(Script1.groovy:2) ~[?:?]
	at com.baidu.hugegraph.loader.executor.GroovyExecutor.execute(GroovyExecutor.java:58) ~[hugegraph-loader-0.12.0.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:158) ~[hugegraph-loader-0.12.0.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:109) [hugegraph-loader-0.12.0.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:73) [hugegraph-loader-0.12.0.jar:?]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "property_key" (class com.baidu.hugegraph.structure.schema.PropertyKey), not marked as ignorable (10 known properties: "check_exist", "status", "properties", "aggregate_type", "name", "user_data", "data_type", "id", "cardinality", "write_type"])
 at [Source: (String)"{"property_key": {"id":1,"name":"id","data_type":"LONG","cardinality":"SINGLE","aggregate_type":"NONE","write_type":"OLTP","properties":[],"status":"CREATED","user_data":{"~create_time":"2022-04-02 17:44:59.867"}}, "task_id": 0}"; line: 1, column: 229] (through reference chain: com.baidu.hugegraph.structure.schema.PropertyKey["property_key"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1686) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1635) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:541) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1390) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.baidu.hugegraph.rest.RestResult.readObject(RestResult.java:62) ~[hugegraph-common-2.0.1.jar:2.0.1.0]
	... 20 more

```

PropertyKeyAPI.create:
https://github.com/hugegraph/hugegraph-client/blob/6f4876f9911362698dfbf2a652f0843df2103bdd/src/main/java/com/baidu/hugegraph/api/schema/PropertyKeyAPI.java#L52

**Comment by javeme** [comment]
The reason is server version updated
