### ISSUE TITLE
图的 propertyKey 更新后导入的问题（报错）

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph-loader#39]
Hi

我用 HugeGraphLoader 的时候起初定义了一个 schema，但由于数据字段的问题报错。

此时，部分 propertyKey 已经成功建立了，因为调用了 `createSchema()` 阶段。

之后重新修改了 `schema.groovy` 文件并重新导入，继续报错：

```java

Vertices has been imported: Exception in thread "main" class com.baidu.hugegraph.exception.NotFoundException: PROPERTY_KEY with name 'my_new_property_key_name' does not exists

    at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java 44)
    ...

    at com.baidu.hugegraph.api.schema.propertyKeyAPI.get(PropertyKeyAPI.java: 64)
    at com.baidu.hugegraph.driver.SchemaManager.getPropertyKey(ElementParser.java:131)
    ..

com.baidu.hugegraph.exception.ServerException: Invalid property 'my_new_property_key_name' for vertex label 'my_label'
    at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java 44) ~ [hugegraph-client-1.6.4.jar:1.6.4.0]
    ...
    ...

```

通过 Restful API 查看，新的属性确实已经建立了。

请问这种原因是？

**Comment by Linary** [comment]
@suesunss 请检查一下 vertex label `my_label` 中确实包含 property `my_new_property_key_name`吗？会不会可能在创建schema的脚本中因为已经创建过`my_label`，第二次执行时因为`ifNotExist()`导致没有创建成功？

**Comment by suesunss** [comment]
@Linary 感谢提醒，这种情况下我确实在第二次又调用了：

```java
schema.vertexLabel("role").properties("id", "my_new_property_key_name").nullableKeys( "my_new_property_key_name").primaryKeys("id").ifNotExist().create();
```
因为调用了 `ifNotExist()`，所以其实没有新增属性。

如果去掉`ifNotExist()`再次用新的属性列表去创建，会报错：

```java
The loading process failed Exception in thread "main" java.lang.reflect.UndeclaredThrowableException at
 com.sun.proxy.$Proxy51.create(Unknown Source) at
 com.baidu.hugegraph.structure.schema.SchemaBuilder$create.call(Unknown Source) at
 org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) at
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) at
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) at
 Script1.run(Script1.groovy:8) at
 com.baidu.hugegraph.loader.executor.GroovyExecutor.execute(GroovyExecutor.java:62) at
 com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:153) at
 com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:109) at
 com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:69) Caused by: java.lang.reflect.InvocationTargetException at
 sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at
 java.lang.reflect.Method.invoke(Method.java:498) at
 com.baidu.hugegraph.structure.schema.BuilderProxy.invoke(BuilderProxy.java:56) ... 10 more Caused by: class com.baidu.hugegraph.exception.ExistedException: The vertex label 'role' has existed at
 com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44) at
 com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63) at
 com.baidu.hugegraph.rest.RestClient.post(RestClient.java:119) at
 com.baidu.hugegraph.rest.RestClient.post(RestClient.java:79) at
 com.baidu.hugegraph.rest.RestClient.post(RestClient.java:74) at
 com.baidu.hugegraph.api.schema.VertexLabelAPI.create(VertexLabelAPI.java:44) at
 com.baidu.hugegraph.driver.SchemaManager.addVertexLabel(SchemaManager.java:103) at
 com.baidu.hugegraph.structure.schema.VertexLabel$BuilderImpl.create(VertexLabel.java:109) at
```

我想问一下，如果是已经创建了 `vertexLabel`，想要新增一个属性，是不是唯一的方法是调用 Restful 的 API：

```java
PUT http://localhost:8080/graphs/hugegraph/schema/vertexlabels/person?action=append
```

（根据文档，目前好像不知道 delete）

可以通过 groovy 的方式去 update 吗？

还有一个问题，如果新增了某个`vertexLabel`的 `propertyKey`，之前导入的数据有影响吗？

**Comment by Linary** [comment]
@suesunss 可以通过groovy为vertexlabel增加属性的，与RESTful API类似，也是用append方法。
```
schema.vertexLabel("role").properties("id", "my_new_property_key_name").nullableKeys( "my_new_property_key_name").primaryKeys("id").ifNotExist().append();
```

> 还有一个问题，如果新增了某个vertexLabel的 propertyKey，之前导入的数据有影响吗？

新添加的属性必须是"nullable"的，就是可空的，所以对之前的数据没有影响。

**Comment by suesunss** [comment]
@Linary 感谢，这点还没有考虑到。

**Comment by suesunss** [comment]
Hi @Linary 

上次这个问题，我尝试了下，如果是 `append()`，大多数情况下 `primaryKeys` 已经创建，所以 groovy 写成

```java
schema.vertexLabel("role").properties("id", "my_new_property_key_name").nullableKeys( "my_new_property_key_name").primaryKeys("id").ifNotExist().append();
```

会报错，提示：

```java
at com.sun.proxy.$Proxy51.append(Unknown Source)
	at com.baidu.hugegraph.structure.schema.SchemaBuilder$append$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at Script1.run(Script1.groovy:19)
	at com.baidu.hugegraph.loader.executor.GroovyExecutor.execute(GroovyExecutor.java:62)
	at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:153)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:109)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:69)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.baidu.hugegraph.structure.schema.BuilderProxy.invoke(BuilderProxy.java:56)
	... 10 more
Caused by: class com.baidu.hugegraph.exception.NotAllowException: Not allowed to update primary keys for vertex label 'id'
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63)
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:142)
	at com.baidu.hugegraph.api.schema.VertexLabelAPI.append(VertexLabelAPI.java:51)
	at com.baidu.hugegraph.driver.SchemaManager.appendVertexLabel(SchemaManager.java:107)
	at com.baidu.hugegraph.structure.schema.VertexLabel$BuilderImpl.append(VertexLabel.java:114)
	at com.baidu.hugegraph.structure.schema.VertexLabel$BuilderImpl.append(VertexLabel.java:92)
	... 15 more
```

如果写成

```java
schema.vertexLabel("role").properties("my_new_property_key_name").nullableKeys( "my_new_property_key_name").ifNotExist().append();
```

是可以的。
