### ISSUE TITLE
点的字段做了映射，loader导入进程卡死，报 schema 错误

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph-loader#40]
Hi,

我尝试用 hugegraph-loader 导入，发现了一个问题。

点的 schema 中，有一个字段是 `role_server`，原始数据文件中，这个字段名是 'server'，所以在 struct 文件中我做了映射：

```json
"vertices": [
      {
        "label": "role",
        "input": {
          "type": "file",
          "path": "role.json",
          "format": "JSON",
          "charset": "UTF-8"
        },
        "mapping": {
          "server": "role_server"
        }
      }
    ],
    ...
}
```

原始文件：

```
{"server":239, "id": ... 
```

这种情况下，我尝试用 loader 导入数据，但进程卡在了点导入完成之后，报 exception 如下：

```java
Edges has been imported: Exception in thread "main" class com.baidu.hugegraph.exception.NotFoundException: PROPERTY_KEY with name 'server' does not exist
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:177)
	at com.baidu.hugegraph.api.schema.PropertyKeyAPI.get(PropertyKeyAPI.java:64)
	at com.baidu.hugegraph.driver.SchemaManager.getPropertyKey(SchemaManager.java:95)
	at com.baidu.hugegraph.loader.parser.ElementParser.getPropertyKey(ElementParser.java:131)
	at com.baidu.hugegraph.loader.parser.ElementParser.validatePropertyValue(ElementParser.java:206)
	at com.baidu.hugegraph.loader.parser.ElementParser.addProperties(ElementParser.java:122)
	at com.baidu.hugegraph.loader.parser.EdgeParser.parse(EdgeParser.java:71)
	at com.baidu.hugegraph.loader.parser.EdgeParser.parse(EdgeParser.java:35)
	at com.baidu.hugegraph.loader.parser.ElementParser.next(ElementParser.java:82)
	at com.baidu.hugegraph.loader.HugeGraphLoader.loadEdge(HugeGraphLoader.java:263)
	at com.baidu.hugegraph.loader.HugeGraphLoader.loadEdges(HugeGraphLoader.java:233)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:120)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:69)
```

我尝试用 rest 去看数据库中的数据，发现点的数据确实已经导入进去了。

`hugegraph-loader.log` 的日志如下：

```
2019-03-11 12:44:31 5899  [main] [INFO ] com.baidu.hugegraph.loader.reader.file.FileReader [] - Ready to open file 'role.json'
2019-03-11 12:45:11 45134 [main] [INFO ] com.baidu.hugegraph.loader.reader.file.FileReader [] - Ready to close file 'role.json'
2019-03-11 12:45:12 46523 [main] [INFO ] com.baidu.hugegraph.loader.task.TaskManager [] - Batch-mode tasks of vertices finished
2019-03-11 12:45:12 46523 [main] [INFO ] com.baidu.hugegraph.loader.task.TaskManager [] - Single-mode tasks of vertices finished
2019-03-11 12:45:12 46527 [main] [INFO ] com.baidu.hugegraph.loader.HugeGraphLoader [] - Loading edge source 'myEdgeLabel'
2019-03-11 12:45:12 46527 [main] [INFO ] com.baidu.hugegraph.loader.reader.file.FileReader [] - Ready to open file 'edge.json'
```

卡在里打开 `edge.json` 文件这一步，loader 的进程也一直卡死，似乎没有 retry。

我尝试把 `--retry-times` 字段的值指定为1，也没有用。

谢谢！

**Comment by Linary** [comment]
@suesunss 请检查一下schema，看看 'server' 这个 PROPERTY_KEY 是否确实存在

**Comment by suesunss** [comment]
@Linary Hi, 我看了下，`server` 这个 propertyKey 不存在，我创建的是 `role_server`，然后在 struct 文件中做了映射。

**Comment by javeme** [comment]
@suesunss 从错误日志来看，像是导入边时发生的错误。请检查下看看是否边的struct配置文件中有`server`属性，或者没有进行mapping？

**Comment by suesunss** [comment]
@javeme 感谢，是我疏忽了，边的原始文件中后来增加了 `server` 字段，感谢提醒，我一直以为是点的问题。
