### ISSUE TITLE
samples import wrong

### ISSUE THREAD

**Issue by yuyongqiang1** [hugegraph/hugegraph-loader#55]
when i download `hugegraph-loader-0.8.0`,then i run the  code from https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html, especially this `bin/hugegraph-loader -g hugegraph -f example/struct.json -s example/schema.groovy`
i meet the follow errors:
```
Exception in thread "main" com.baidu.hugegraph.rest.SerializeException: Failed to deserialize json
	at com.baidu.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:65)
	at com.baidu.hugegraph.loader.source.GraphSource.of(GraphSource.java:49)
	at com.baidu.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:76)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:68)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unrecognized field "skipped_line_regex" (class com.baidu.hugegraph.loader.source.file.FileSource), not marked as ignorable (6 known properties: "path", "format", "comment_symbols", "charset", "header", "delimiter"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.baidu.hugegraph.loader.source.file.FileSource["skipped_line_regex"]) (through reference chain: com.baidu.hugegraph.loader.source.GraphSource["vertices"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:360)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:308)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at com.baidu.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:63)
	... 3 more
Caused by: java.lang.IllegalArgumentException: Unrecognized field "skipped_line_regex" (class com.baidu.hugegraph.loader.source.file.FileSource), not marked as ignorable (6 known properties: "path", "format", "comment_symbols", "charset", "header", "delimiter"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.baidu.hugegraph.loader.source.file.FileSource["skipped_line_regex"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3589)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3508)
	at com.baidu.hugegraph.loader.serializer.InputSourceDeserializer.read(InputSourceDeserializer.java:32)
	at com.baidu.hugegraph.loader.serializer.FileSourceDeserializer.deserialize(FileSourceDeserializer.java:45)
	at com.baidu.hugegraph.loader.serializer.FileSourceDeserializer.deserialize(FileSourceDeserializer.java:30)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3584)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3508)
	at com.baidu.hugegraph.loader.util.JsonUtil.convert(JsonUtil.java:70)
	at com.baidu.hugegraph.loader.serializer.ElementSourceDeserializer.readInputSource(ElementSourceDeserializer.java:43)
	at com.baidu.hugegraph.loader.serializer.VertexSourceDeserializer.deserialize(VertexSourceDeserializer.java:52)
	at com.baidu.hugegraph.loader.serializer.VertexSourceDeserializer.deserialize(VertexSourceDeserializer.java:35)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	... 12 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "skipped_line_regex" (class com.baidu.hugegraph.loader.source.file.FileSource), not marked as ignorable (6 known properties: "path", "format", "comment_symbols", "charset", "header", "delimiter"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.baidu.hugegraph.loader.source.file.FileSource["skipped_line_regex"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1094)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1470)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1448)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3584)
	... 23 more
```

**Comment by javeme** [comment]
@yuyongqiang1 you may use struct format of new version v0.9. please try to remove the skipped_line_regex from example/struct.json.

**Comment by javeme** [comment]
> @yuyongqiang1 you may use struct format of new version v0.9. please try to remove the skipped_line_regex from example/struct.json.
