### ISSUE TITLE
process doesn't exit during element building process when schema is not correct

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph-loader#76]
三月份的时候谈到过一个[类似的问题](https://github.com/hugegraph/hugegraph-loader/issues/40)，现在发现这里确实有些不合理的处理。

# 问题复现

拿 loader 自带的 examples 举例，struct 文件的配置是：

```json
{
  "edges": [
    {
      "label": "knows",
      "source": ["source_name"],
      "target": ["target_name"],
      "input": {
        "type": "file",
        "path": "example/file/edge_knows.json",
        "format": "JSON",
        "date_format": "yyyyMMdd"
      },
      "mapping": {
        "source_name": "name",
        "target_name": "name"
      }
    },
    {
      "label": "created",
      "source": ["source_name"],
      "target": ["target_id"],
      "input": {
        "type": "file",
        "path": "example/file/edge_created.json",
        "format": "JSON",
        "date_format": "yyyy-MM-dd"
      }
    }
  ]
}
```
这里，由于原始文件的列名和图的 schema 对应的属性名不一致，进行了映射，把 `source_name` 和 `target_name`分别映射成了 `name`。

但是，如果我们在配置的时候，忘记了配置 mapping，就会在导入的时候抛出异常：
```java
Vertices has been imported: 8
Edges has been imported: Exception in thread "main" class com.baidu.hugegraph.exception.NotFoundException: PROPERTY_KEY with name 'source_name' does not exist
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:69)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:200)
	at com.baidu.hugegraph.api.schema.PropertyKeyAPI.get(PropertyKeyAPI.java:64)
	at com.baidu.hugegraph.driver.SchemaManager.getPropertyKey(SchemaManager.java:95)
	at com.baidu.hugegraph.loader.builder.ElementBuilder.getPropertyKey(ElementBuilder.java:143)
	at com.baidu.hugegraph.loader.builder.ElementBuilder.validatePropertyValue(ElementBuilder.java:206)
	at com.baidu.hugegraph.loader.builder.EdgeBuilder.buildVertexId(EdgeBuilder.java:113)
	at com.baidu.hugegraph.loader.builder.EdgeBuilder.build(EdgeBuilder.java:61)
	at com.baidu.hugegraph.loader.builder.EdgeBuilder.build(EdgeBuilder.java:34)
	at com.baidu.hugegraph.loader.builder.ElementBuilder.next(ElementBuilder.java:89)
	at com.baidu.hugegraph.loader.HugeGraphLoader.loadEdge(HugeGraphLoader.java:271)
	at com.baidu.hugegraph.loader.HugeGraphLoader.loadEdges(HugeGraphLoader.java:241)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:131)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:80)
```
但问题是，loader进程并没有在这里退出，而是 hang 在了这里。观察 loader 的源代码（`ElementBuilder.java`），发现：

```java
 protected PropertyKey getPropertyKey(String name) {
        SchemaElement schema = this.schemas.get(HugeType.PROPERTY_KEY, name);
        if (schema == null) {
            schema = this.client.schema().getPropertyKey(name);
        }
        E.checkState(schema != null, "The property key %s doesn't exist", name);
        this.schemas.put(HugeType.PROPERTY_KEY, name, schema);
        return (PropertyKey) schema;
    }
```
这里使用 `this.client.schema()`根据 name获取对应的 schema，程序并没有走到：
```java 
E.checkState(schema != null, "The property key %s doesn't exist", name);
```
这里，而是卡在了 `getPropertyKey(name)`那里。如果我们的使用场景是使用脚本进行导入，就会出现进程长时间挂起不能因为这个异常自动退出的情况。

# 问题分析
通过分析 trace 发现，链路中调用了 `hugegraph-client-1.7.0-source.jar` 中的 `RestClient.java` 中的 `checkStatus(Response response, Response.Status... statuses)` 方法：
```java
protected void checkStatus(Response response, Response.Status... statuses) {
        boolean match = false;
        for (Response.Status status : statuses) {
            if (status.getStatusCode() == response.getStatus()) {
                match = true;
                break;
            }
        }
        if (!match) {
            throw ServerException.fromResponse(response);
        }
    }
```
我们看到，这里，如果 `match == false`，将会 `throw ServerException`，若在一个条件语句中抛出异常，则程序能被编译，但后面的语句不会被执行，这也就是：
```java
E.checkState(schema != null, "The property key %s doesn't exist", name);
```
不能被执行，进程挂起的原因。

个人觉得，`checkStatus` 方法里，如果不能 match，程序直接退出是不是更好，否则，需要在外层函数显式地捕获这个 `ServerException` （比如可能使用到的 hugegraph-client 和 hugegraph-loader）。

**Comment by Linary** [comment]
@suesunss 非常感谢使用以及反馈。

这里的`RestClient.java`是属于`hugegraph-client`模块，其定位仍然更接近于工具类，如果直接退出那就是给用户提前做决定了，这样即使用户想在外层捕获异常，然后继续往下走创建这个`propertykey`也做不到了。这里的问题我认为还是出在`loader`本身，应该捕获住这个`ServerException`，然后处理（退出或是抛出`LoadException`）。

其实这里的一个更值得注意的讨论点是：`schema().getPropertyKey(name)`这个请求发到服务端之后，如果发现不存在这个`propertykey`，服务端是应该返回`null`还是应该抛出异常。

**Comment by javeme** [comment]
看起来映射文件没有配置正确的话，程序报错退出是更合理的。

**Comment by suesunss** [comment]
@javeme @Linary 是的，在 loader 端报错退出感觉更合理一些，另外 `ElementBuilder.java` `addProperties 方法` 里面也由类似的问题，对应的表现就是如果 `source` 和 `target` 字段填写错误也会出现进程挂起的问题。
